name: Compile MicroPython for boards/esp32_s3_wroom_1_n16r8.yml

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      env:
        BOARD: ESP32_S3
        BOARD_DIR: boards/${BOARD}
        BUILD_DIR: boards/${BOARD}/build
        PORT_DIR: lib/micropython/ports/esp32
  
      steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # submodules: 'recursive' is inefficient, as it checks out many submodules we don't need
          submodules: ''

      - name: Checkout required submodules
        run: |
          echo BOARD=${BOARD}
          git submodule update --init lib/micropython
          cd lib/micropython; git submodule update --init lib/berkeley-db-1.xx lib/micropython-lib
      
      - name: Compile (in esp-idf docker)
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:v5.0.4
          shell: bash
          options: -v ${{ github.workspace }}:/project -w /project -e BOARD=ESP32_S3 -e BOARD_DIR=${BOARD_DIR} -e BUILD_DIR=${BUILD_DIR} -e PORT_DIR=${PORT_DIR}
          run: |
              . $IDF_PATH/export.sh
              env
              make -C /project/lib/micropython/mpy-cross
              cd /project/boards/ESP32_S3
              pwd
              idf.py build
              cd /project/lib/micropython/ports/esp32
              pwd
              python makeimg.py \
                /project/boards/ESP32_S3/build/sdkconfig \
                /project/boards/ESP32_S3/build/bootloader/bootloader.bin \
                /project/boards/ESP32_S3/build/partition_table/partition-table.bin \
                /project/boards/ESP32_S3/build/micropython.bin \
                /project/boards/ESP32_S3/build/firmware.bin \
                /project/boards/ESP32_S3/build/micropython.uf2
              ls -l /project/boards/ESP32_S3/build/*.bin /project/boards/ESP32_S3/build/*.uf2

      - name: Release
        working-directory: ${BUILD_DIR}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          cd ${BUILD_DIR}
          pwd
          ls -l *bin *uf2
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} MicroPython ${BOARD} ${tag#v}" \
              --generate-notes \
              micropython.bin \
              firmware.bin \
              micropython.uf2
              
      

