name: Compile MicroPython for boards/esp32_s3_wroom_1_n16r8.yml

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      env:
        BOARD: ESP32_S3
        BOARD_DIR: boards/${BOARD}
        BUILD_DIR: boards/${BOARD}/build
        PORT_DIR: lib/micropython/ports/esp32
  
      steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # submodules: 'recursive' is inefficient, as it checks out many submodules we don't need
          submodules: ''

      - name: Checkout required submodules
        run: |
          git submodule update --init lib/micropython
          cd lib/micropython; git submodule update --init lib/berkeley-db-1.xx lib/micropython-lib
      
      - name: Compile (in esp-idf docker)
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:v5.0.4
          options: -v ${{ github.workspace }}:/project -w /project -e BOARD=${BOARD} -e BOARD_DIR=${BOARD_DIR} -e BUILD_DIR=${BUILD_DIR} -e PORT_DIR=${PORT_DIR}
          run: |
              echo BOARD=$(BOARD)
              make -C /project/lib/micropython/mpy-cross
              cd /project/boards/$(BOARD_DIR)
              pwd
              idf.py build
              cd /project/$(PORT_DIR) \
              pwd
              python makeimg.py \
                /project/$(BUILD_DIR)/sdkconfig \
                /project/$(BUILD_DIR)/bootloader/bootloader.bin \
                /project/$(BUILD_DIR)/partition_table/partition-table.bin \
                /project/$(BUILD_DIR)/micropython.bin \
                /project/$(BUILD_DIR)/firmware.bin \
                /project/$(BUILD_DIR)/micropython.uf2

      - name: Release
        working-directory: ${{ env.BUILD_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          cd ${{ env.BUILD_DIR }} && \
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} MicroPython $${{ env.BOARD }} ${tag#v}" \
              --generate-notes \
              micropython.bin \
              firmware.bin \
              micropython.uf2
              
      

