name: Compile MicroPython for boards/esp32_s3

on:
  push:
    tags:
      - '**'

env:
    BOARD: ESP32_S3



permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:

        - name: Define env
          run: |
            echo "BOARD=${BOARD}" >> $GITHUB_ENV
            echo "BOARD_DIR=boards/${{ env.BOARD }}" >> $GITHUB_ENV
            echo "BUILD_DIR=boards/${{ env.BOARD }}/build" >> $GITHUB_ENV
            echo "PORT_DIR=lib/micropython/ports/esp32" >> $GITHUB_ENV

        - name: Use env
          run: |
            echo BOARD a=${BOARD}
            echo BOARD b=${{ env.BOARD }}
            echo BOARD_DIR=${{ env.BOARD_DIR }}
            echo BUILD_DIR=${{ env.BUILD_DIR }}
            echo PORT_DIR=${{ env.PORT_DIR }}

        - name: Checkout
          uses: actions/checkout@v4

        - name: Checkout required submodules
          run: |
            git submodule update --init lib/micropython
            cd lib/micropython; git submodule update --init lib/berkeley-db-1.xx lib/micropython-lib

        - name: Copy boards to PORT_DIR/boards
          run: |
            mkdir -p ${{ env.PORT_DIR }}/boards
            cp -r ${{ env.BOARD_DIR }} ${{ env.PORT_DIR }}/boards
            cp -a ${{ env.BOARD_DIR }} ${{ env.PORT_DIR }}/boards
            cd ${{ env.PORT_DIR }}/boards
            ls -l
            cd ${{ env.BOARD }}
            ls -l
        
        - name: Release
          # working-directory: ${BUILD_DIR}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
          run: |
            pwd
            ls -l
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} MicroPython ${BOARD} ${tag#v}" \
                --generate-notes \
                README.md
                
          
    