name: Compile MicroPython for boards/esp32_s3_wroom_1_n16r8.yml

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
    BOARD: ESP32_S3



permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:

        - name: env
          run: |
            echo "BOARD=${BOARD}" >> $GITHUB_ENV
            echo "BOARD_DIR=boards/${{ env.BOARD }}" >> $GITHUB_ENV
            echo "BUILD_DIR=${{ env.BOARD_DIR }}/build" >> $GITHUB_ENV
            echo "PORT_DIR=lib/micropython/ports/esp32" >> $GITHUB_ENV

        - name: Use env
          run: |
            echo BOARD a=${BOARD}
            echo BOARD b=${{ env.BOARD }}
            echo BOARD_DIR ${{ env.BOARD_DIR }}
            echo BUILD_DIR ${{ env.BUILD_DIR }}
            echo PORT_DIR ${{ env.PORT_DIR }}

