name: Compile MicroPython for boards/esp32_s3_wroom_1_n16r8.yml

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
    BOARD: ESP32_S3
    BOARD_DIR: boards/${BOARD}
    BUILD_DIR: ${BOARD_DIR}/build
    PORT_DIR: lib/micropython/ports/esp32


permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:

        - name: env
          run: |
            echo BOARD=${BOARD}
            echo BOARD_DIR=${BOARD_DIR}
            echo BUILD_DIR=${BUILD_DIR}
            echo PORT_DIR=${PORT_DIR}
            env
            pwd

