name: Compile MicroPython for boards/esp32_s3_wroom_1_n16r8.yml

on:
  push:
    tags:
      - '**'

env:
    BOARD: ESP32_S3



permissions:
  contents: write
      
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:

        - name: Define env
          run: |
            echo "BOARD=${BOARD}" >> $GITHUB_ENV
            echo "BOARD_DIR=boards/${{ env.BOARD }}" >> $GITHUB_ENV
            echo "BUILD_DIR=boards/${{ env.BOARD }}/build" >> $GITHUB_ENV
            echo "PORT_DIR=lib/micropython/ports/esp32" >> $GITHUB_ENV

        - name: Use env
          run: |
            echo BOARD a=${BOARD}
            echo BOARD b=${{ env.BOARD }}
            echo BOARD_DIR=${{ env.BOARD_DIR }}
            echo BUILD_DIR=${{ env.BUILD_DIR }}
            echo PORT_DIR=${{ env.PORT_DIR }}

        - name: Release
          uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            body: |
              Changes in this Release
            draft: false
            prerelease: false

        - name: Release
          working-directory: ${BUILD_DIR}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
          run: |
            echo "Building MicroPython for ${BOARD}" > test.txt
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} MicroPython ${BOARD} ${tag#v}" \
                --generate-notes \
                test.txt
                
          
    